CREATE DATABASE IF NOT EXISTS `db_data`;

USE `db_data`;

CREATE TABLE IF NOT EXISTS daftar (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(255) NOT NULL,
    alamat VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS contact (
    names VARCHAR(255) NOT NULL,
    mail VARCHAR(255) NOT NULL,
    subjek VARCHAR(255) NOT NULL,
    pesan VARCHAR(500) NOT NULL
);